import type { CaseEventRecord, CaseRecord } from '@/types/database.types';

export const INITIAL_CASES: CaseRecord[] = [
  {
    id: 'c101',
    public_id: 'PA-001824',
    reporter_id: 'user-01',
    jurisdiction_id: 'sac-01',
    agency_id: 'dpw-01',
    title: 'Deep axle-breaker pothole at intersection',
    description: 'Pothole on the eastbound lane right before the crosswalk. Over 4 inches deep.',
    category: 'POTHOLE',
    location: { lat: 38.57283, lng: -121.48291 },
    address: 'Broadway & 21st St, Sacramento, CA',
    community_status: 'OPEN',
    official_status: 'IN_PROGRESS',
    severity: 'DANGEROUS',
    confirmation_count: 43,
    follower_count: 27,
    comment_count: 8,
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    submitted_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    resolved_at: null,
  },
  {
    id: 'c102',
    public_id: 'PA-001825',
    reporter_id: 'user-02',
    jurisdiction_id: 'sac-01',
    agency_id: 'dpw-01',
    title: 'Severe asphalt crumbling along bike lane',
    description:
      'Long trench where asphalt has collapsed. Multiple cyclists swerving into traffic.',
    category: 'POTHOLE',
    location: { lat: 38.5681, lng: -121.4722 },
    address: 'J Street & 16th St, Sacramento, CA',
    community_status: 'CONFIRMED',
    official_status: 'SUBMITTED',
    severity: 'SIGNIFICANT',
    confirmation_count: 19,
    follower_count: 12,
    comment_count: 3,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    submitted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    resolved_at: null,
  },
  {
    id: 'c103',
    public_id: 'PA-001826',
    reporter_id: 'user-03',
    jurisdiction_id: 'sac-01',
    agency_id: 'dpw-01',
    title: 'Fixed pothole verified by community',
    description: 'Road crew patched the sunken section this morning.',
    category: 'POTHOLE',
    location: { lat: 38.5795, lng: -121.4912 },
    address: 'K Street & 10th St, Sacramento, CA',
    community_status: 'RESOLVED',
    official_status: 'CLOSED',
    severity: 'MINOR',
    confirmation_count: 31,
    follower_count: 15,
    comment_count: 5,
    created_at: new Date(Date.now() - 28 * 86400000).toISOString(),
    submitted_at: new Date(Date.now() - 26 * 86400000).toISOString(),
    resolved_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];

export const INITIAL_EVENTS: CaseEventRecord[] = [
  {
    id: 'e1',
    case_id: 'c101',
    event_type: 'REPORTED',
    actor_type: 'USER',
    actor_id: 'user-01',
    payload: { note: 'Initial photograph captured with location proof' },
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'e2',
    case_id: 'c101',
    event_type: 'CONFIRMATIONS_THRESHOLD',
    actor_type: 'SYSTEM',
    actor_id: null,
    payload: { count: 8, note: '8 neighbors confirmed this road defect' },
    created_at: new Date(Date.now() - 13 * 86400000).toISOString(),
  },
  {
    id: 'e3',
    case_id: 'c101',
    event_type: 'SUBMITTED_TO_AGENCY',
    actor_type: 'SYSTEM',
    actor_id: null,
    payload: { agency: 'Sacramento Public Works', ticket_id: '311-938271' },
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: 'e4',
    case_id: 'c101',
    event_type: 'AGENCY_ACKNOWLEDGED',
    actor_type: 'AGENCY',
    actor_id: 'dpw-01',
    payload: { notes: 'Assigned to District 4 maintenance depot' },
    created_at: new Date(Date.now() - 11 * 86400000).toISOString(),
  },
];
